nodeLinker: node-modules
enableGlobalCache: true
enableScripts: true

packageExtensions:
  "@react-email/components@*":
    dependencies:
      react-dom: "*"
  "@tiptap/react@*":
    dependencies:
      "@floating-ui/dom": "^1.0.0"
